CREATE TABLE [dbo].[Lead]
(
	[AgentId] int not null default(0),
    [Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[CompanyName] nvarchar(max),
	[ContactPersonName] nvarchar(max),
	[ContactPersonNumber] nvarchar(max),
	[CompanyId] int,
	[Name] nvarchar(max),
	[Domain] int,
	[Address] nvarchar(max),
	[Contact]  nvarchar (max) ,
	[Email]  nvarchar (max) ,
	[AlternateNumber] nvarchar(max),
	[Website] nvarchar(max),
	[Area] int,
	[City] int,
	[Description] nvarchar(max),
	[ModeOfCommunication] int,
	[BusinessOperationTime] int,
	[NoEmployee] int,
	[BusinessIndustry] int,
	[CurrentItPlatform] nvarchar(max),
	[CUDS]int,
	[CUDSService] int,
	[CUDSOtherService] nvarchar(max),
	[NoLinks] int,
	[NTN] nvarchar(max),
	[NumberOfBranchOffices] int,
	[EstimatedClosingDate] datetime,
	[IsEsisting] bit,
	[HasTriedOurServie] bit,
	[Comments] nvarchar(max),
	[Budget] decimal(18,3),
	
	[AssignedPmdId] int,
	[PmdAssignedOn] DateTime,
	[PresaleAssignedOn] DateTime,
	[LeadAssignedOn] DateTime,
	[AssignedPreSaleId] int,
	[AssignedToId] int,
	[LeadRemarks] nvarchar(max),
	[LeadStatus] int,
	[PmdStatus] int,
	[PmdRemarks] nvarchar(max),
	[QuotationStatus] int,
	[QuotationRemarks] nvarchar(max),
	[IsApproved] bit,
	[AdminRemarks] nvarchar(max),
	
	
	[CreatedBy] nvarchar(max),
	[CreatedAt] DateTime,
	[UpdatedBy] nvarchar(max),
	[UpdatedAt] DateTime,
	Constraint [FK_Lead_Company] foreign key ([CompanyId]) References [dbo].[Company] ([Id]),
	Constraint [FK_Lead_Agent_PMD] foreign key ([AssignedPmdId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_Lead_Agent_PreSale] foreign key ([AssignedPreSaleId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_Lead_Agent_Lead] foreign key ([AssignedToId]) References [dbo].[Agent] ([Id]),
	Constraint [FK_Lead_Agent_Creator] foreign key ([AgentId]) References [dbo].[Agent] ([Id]),
)
