CREATE TABLE [dbo].[Lead]
(
	[Id] INT NOT NULL PRIMARY KEY Identity(1,1),
	[CompanyName] nvarchar(max),
	[ContactPersonName] nvarchar(max),
	[ContactPersonNumber] nvarchar(max),
    [AlternateNumber] nvarchar(max),
	[ModeOfCommunication] int,
	[BusinessTime] int,
	[Website] nvarchar(max),
	[Email] nvarchar(max),
	[City] nvarchar(max),
	[Area] nvarchar(max),
	[Address] nvarchar(max),
	[NoOfEmployee] int,
	[NumberOfBranches] int,
	[BusinessSegmentaion] int, 
	[NtnNumber] nvarchar(max),
	[IsExistingCustomer] bit,
	[CurrentServiceProviderType] int,
	[CurrentServiceProviderName] nvarchar(max),
	[NumberOfLinks] int,
	[LeadRemarks] nvarchar(max),
	[LeadStatus] int,
	[PmdStatus] int,
	[QuotationStatus] int,
	[IsApproved] bit,
	[AdminRemarks] nvarchar(max),
	[PmdRemarks] nvarchar(max),
	[QuotationRemarks] nvarchar(max),
	[Latitude] float,
	[Longitude] float,
	[BandwidthRequirement] nvarchar(max),
	[BuildingHeight] float,
	[ExpectedDeliveryTimeline] datetime,
	[CreatedBy] nvarchar(max),
	[CreatedAt] DateTime,
	[UpdatedBy] nvarchar(max),
	[UpdatedAt] DateTime,


)
