//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lead()
        {
            this.PmdDetails = new HashSet<PmdDetails>();
        }
    
        public int Id { get; set; }
        public string CompanyName { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactPersonNumber { get; set; }
        public string AlternateNumber { get; set; }
        public Nullable<int> ModeOfCommunication { get; set; }
        public Nullable<int> BusinessTime { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string City { get; set; }
        public string Area { get; set; }
        public string Address { get; set; }
        public Nullable<int> NoOfEmployee { get; set; }
        public Nullable<int> NumberOfBranches { get; set; }
        public Nullable<int> BusinessSegmentaion { get; set; }
        public string NtnNumber { get; set; }
        public Nullable<bool> IsExistingCustomer { get; set; }
        public Nullable<int> CurrentServiceProviderType { get; set; }
        public string CurrentServiceProviderName { get; set; }
        public Nullable<int> NumberOfLinks { get; set; }
        public string LeadRemarks { get; set; }
        public Nullable<int> LeadStatus { get; set; }
        public Nullable<int> PmdStatus { get; set; }
        public Nullable<int> QuotationStatus { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string AdminRemarks { get; set; }
        public string PmdRemarks { get; set; }
        public string QuotationRemarks { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public string BandwidthRequirement { get; set; }
        public Nullable<double> BuildingHeight { get; set; }
        public Nullable<System.DateTime> ExpectedDeliveryTimeline { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PmdDetails> PmdDetails { get; set; }
    }
}
