//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMS.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sharptel_Lms_DbEntities : DbContext
    {
        public Sharptel_Lms_DbEntities()
            : base("name=Sharptel_Lms_DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<CompanyBranches> CompanyBranches { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<PmdDetails> PmdDetails { get; set; }
        public virtual DbSet<Vendor> Vendor { get; set; }
        public virtual DbSet<Company> Company { get; set; }
        public virtual DbSet<Lead> Lead { get; set; }
        public virtual DbSet<SolutionDetails> SolutionDetails { get; set; }
    }
}
